config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def index
    @dog = Dog.new
    @dogs = Dog.all
  end

  def create
    @dog = Dog.create(dog_params)
    if @dog.save
      redirect_to dogs_path
    else
      render :index
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update_attributes!(dog_params)

    redirect_to dogs_path
  end

  def destroy
    @dog = Dog.find(params[:id]).delete

    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:dog_name, :dog_color)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/edit.html.erb
<%= form_for @dog do |f| %>
  <p>
    <%= f.label :dog_name %>
    <%= f.text_field :dog_name %>
  </p>
  <p>
    <%= f.label :dog_color %>
    <%= f.text_field :dog_color %>
  </p>
  <p>
    <%= f.submit 'Update dog' %>
  </p>
<% end %>

app/views/dogs/index.html.erb
<%= form_for @dog do |f| %>
  <p>
    <%= f.label :dog_name %>
    <%= f.text_field :dog_name %>
  </p>
  <p>
    <%= f.label :dog_color %>
    <%= f.text_field :dog_color %>
  </p>
  <p>
    <%= f.submit 'Create Dog' %>
  </p>
<% end %>

<% @dogs.each do |dog| %>
<ul>
  <li>
    <%= dog.dog_name %>, <%= dog.dog_color %>
  </li>
</ul>
<% end %>

app/views/dogs/show.html.erb
<ul>
  <li>
    <%= @dog.dog_name %>, <%= @dog.dog_color %>
  </li>
</ul>

<%= link_to 'Edit dog', edit_dog_path(@dog) %>
<%= link_to 'Delete dog', dog_path(@dog), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudDogs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<%= link_to 'Add Dog', dogs_path %>